### ISSUE TITLE
Availability

### ISSUE THREAD

**Issue by foebu** [aliuy/grphin#2]
Hi! Are these data still accessible anywhere? Thanks!

**Comment by aliuy** [comment]
I believe michaelfy's dataset got taken down by LinkedIn :(

**Comment by apockill** [comment]
Oh no! Is there no way anyone might have a mirror? I'm dying here, I would love this data for a school project.

**Comment by scrat4acorn** [comment]
Is it possible to reupload? I'd be able to provide a onedrive where you could upload. Would love this data for a research project!

**Comment by fcmercury** [comment]
https://www.reuters.com/article/us-microsoft-linkedin-ruling-idUSKCN1AU2BV?il=0&utm_source=reddit.com
U.S. judge says LinkedIn cannot block startup from public profile data
